sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: czEfHQlvPAAG6Ejss68ikvrXwjoNCB3Z0jD5pmy3cuE9YWEoAZfNd/gGR3rM8iXe/VCMwAeuJdUUyY+XbU8Y6+d/zOVaSpTmdlusmQRnTGyjCcv/MPdAmAGSvv8foH1dxqtiPZnYTKkit2U+NmTqVK03aWIDz5xhIb+bdrvp3wLBvGCpl7ZdPjWswW7DTzVgXEOx7oYhAPPVktadhb4Zrz8W7eNA25r4k7lDw75GqH6wi6HQ6WXnzPndFiCW7fUYuZF9OeZK0F9tq6zh/YCTWKDztlTEfLwnNRoISskSZBdQjVV4Zx00jwMhDGtWPqzlZH4tn5njCjQT0X2ckjMygvFXpxGbpyXN4XALo0QbayPpprb3x7yIlmIN08N73n6By85OQrz2x/z6meIEJ+96GVNrbvxkkABhFsT90Naa3VpGqMTuo+kbakK9VfaS4rWteCQgwUkwIZhAtg7F6uqtTd6BcKyYAKVaavviiiEf71/Qi3O0I//iJ3GV5ez9ZIqpsnq2XyZG/Mt68P4JdzeUOKD29zyPIGTMT7OMPDtRlugKdnUoSUe+Ei0OFE+Shs3Dp9nArkbh9pQP55wQz6bczPYYij+vtzdNhyJXd7AMX3jBSRMYBddzJBbnG7dXILrqc+F1qZSG6rqGGKWhA6Fic/eOGxLxZXbE2+LjN0rRLNM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Veranilda_4306
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy